In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [3]:
Telco = pd.read_csv("Telco-Customer-Churn.csv")
Telco

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [4]:
Telco.isnull()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7042,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [3]:
Yes_No_Maping_1 = {"Yes" : 1, "No" : 0}
Yes_No_Maping_2 = {"Yes" : 1, "No" : 0, "No internet service" : 0}
Yes_No_Maping_3 = {"Yes" : 1, "No" : 0, "No phone service" : 0}
Yes_No_Maping_4 = {"DSL" : 1, "Fiber optic" : 2, "No" : 0}
Yes_No_Maping_5 = {"Month-to-month" : "MM", "One year" : "OY", "Two year" : "TY"}
Yes_No_Maping_6 = {"Electronic check" : "E-Check","Bank transfer (automatic)" : "Banck", "Mailed check" : "M-Check", "Credit card (automatic)" : "Card"}

Telco["Partner"] = Telco["Partner"].map(Yes_No_Maping_1)
Telco["Dependents"] = Telco["Dependents"].map(Yes_No_Maping_1)
Telco["PhoneService"] = Telco["PhoneService"].map(Yes_No_Maping_1)
Telco["PaperlessBilling"] = Telco["PaperlessBilling"].map(Yes_No_Maping_1)
Telco["Churn"] = Telco["Churn"].map(Yes_No_Maping_1)
Telco["OnlineSecurity"] = Telco["OnlineSecurity"].map(Yes_No_Maping_2)
Telco["OnlineBackup"] = Telco["OnlineBackup"].map(Yes_No_Maping_2)
Telco["DeviceProtection"] = Telco["DeviceProtection"].map(Yes_No_Maping_2)
Telco["TechSupport"] = Telco["TechSupport"].map(Yes_No_Maping_2)
Telco["StreamingTV"] = Telco["StreamingTV"].map(Yes_No_Maping_2)
Telco["StreamingMovies"] = Telco["StreamingMovies"].map(Yes_No_Maping_2)
Telco["MultipleLines"] = Telco["MultipleLines"].map(Yes_No_Maping_3)
Telco["InternetService"] = Telco["InternetService"].map(Yes_No_Maping_4)
Telco["Contract"] = Telco["Contract"].map(Yes_No_Maping_5)
Telco["PaymentMethod"] = Telco["PaymentMethod"].map(Yes_No_Maping_6)

Sex = pd.get_dummies(Telco["gender"], drop_first = True)
D_Contract = pd.get_dummies(Telco["Contract"], drop_first = True)
Payment = pd.get_dummies(Telco["PaymentMethod"], drop_first = True)

Telco = pd.concat([Telco, Sex, D_Contract , Payment], axis = 1)

Telco.drop(["customerID", "gender", "PaymentMethod", "Contract", "TotalCharges"], axis = 1, inplace = True)

Telco

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,...,StreamingMovies,PaperlessBilling,MonthlyCharges,Churn,Male,OY,TY,Card,E-Check,M-Check
0,0,1,0,1,0,0,1,0,1,0,...,0,1,29.85,0,0,0,0,0,1,0
1,0,0,0,34,1,0,1,1,0,1,...,0,0,56.95,0,1,1,0,0,0,1
2,0,0,0,2,1,0,1,1,1,0,...,0,1,53.85,1,1,0,0,0,0,1
3,0,0,0,45,0,0,1,1,0,1,...,0,0,42.30,0,1,1,0,0,0,0
4,0,0,0,2,1,0,2,0,0,0,...,0,1,70.70,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,1,24,1,1,1,1,0,1,...,1,1,84.80,0,1,1,0,0,0,1
7039,0,1,1,72,1,1,2,0,1,1,...,1,1,103.20,0,0,1,0,1,0,0
7040,0,1,1,11,0,0,1,1,0,0,...,0,1,29.60,0,0,0,0,0,1,0
7041,1,1,0,4,1,1,2,0,0,0,...,0,1,74.40,1,1,0,0,0,0,1
7042,0,0,0,66,1,0,2,1,0,1,...,1,1,105.65,0,1,0,1,0,0,0

In [4]:
X = Telco.drop(["Churn"], axis = 1)
Y = Telco.Churn

In [5]:
X.head(20)

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,...,StreamingTV,StreamingMovies,PaperlessBilling,MonthlyCharges,Male,OY,TY,Card,E-Check,M-Check
0,0,1,0,1,0,0,1,0,1,0,...,0,0,1,29.85,0,0,0,0,1,0
1,0,0,0,34,1,0,1,1,0,1,...,0,0,0,56.95,1,1,0,0,0,1
2,0,0,0,2,1,0,1,1,1,0,...,0,0,1,53.85,1,0,0,0,0,1
3,0,0,0,45,0,0,1,1,0,1,...,0,0,0,42.30,1,1,0,0,0,0
4,0,0,0,2,1,0,2,0,0,0,...,0,0,1,70.70,0,0,0,0,1,0
5,0,0,0,8,1,1,2,0,0,1,...,1,1,1,99.65,0,0,0,0,1,0
6,0,0,1,22,1,1,2,0,1,0,...,1,0,1,89.10,1,0,0,1,0,0
7,0,0,0,10,0,0,1,1,0,0,...,0,0,0,29.75,0,0,0,0,0,1
8,0,1,0,28,1,1,2,0,0,1,...,1,1,1,104.80,0,0,0,0,1,0
9,0,0,1,62,1,0,1,1,1,0,...,0,0,0,56.15,1,1,0,0,0,0
10,0,1,1,13,1,0,1,1,0,0,...,0,0,1,49.95,1,0,0,0,0,1
11,0,0,0,16,1,0,0,0,0,0,...,0,0,0,18.95,1,0,1,1,0,0
12,0,1,0,58,1,1,2,0,0,1,...,1,1,0,100.35,1,1,0,1,0,0
13,0,0,0,49,1,1,2,0,1,1,...,1,1,1,103.70,1,0,0,0,0,0
14,0,0,0,25,1,0,2,1,0,1,...,1,1,1,105.50,1,0,0,0,1,0
15,0,1,1,69,1,1,2,1,1,1,...,1,1,0,113.25,0,0,1,1,0,0
16,0,0,0,52,1,0,0,0,0,0,...,0,0,0,20.65,0,1,0,0,0,1
17,0,0,1,71,1,1,2,1,0,1,...,1,1,0,106.70,1,0,1,0,0,0
18,0,1,1,10,1,0,1,0,0,1,...,0,0,0,55.20,0,0,0,1,0,0
19,0,0,0,21,1,0,2,0,1,1,...,0,1,1,90.05,0,0,0,0,1,0

In [6]:
Telco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SeniorCitizen     7043 non-null   int64
 1   Partner           7043 non-null   int64
 2   Dependents        7043 non-null   int64
 3   tenure            7043 non-null   int64
 4   PhoneService      7043 non-null   int64
 5   MultipleLines     7043 non-null   int64
 6   InternetService   7043 non-null   int64
 7   OnlineSecurity    7043 non-null   int64
 8   OnlineBackup      7043 non-null   int64
 9   DeviceProtection  7043 non-null   int64
 10  TechSupport       7043 non-null   int64
 11  StreamingTV       7043 non-null   int64
 12  StreamingMovies   7043 non-null   int64
 13  PaperlessBilling  7043 non-null   int64
 14  MonthlyCharges    7043 non-null   float64
 15  Churn             7043 non-null   int64
 16  Male              7043 non-null   uint8
 17  OY                7043 non-null   uint8
 18  TY                7043 non-null   uint8
 19  Card              7043 non-null   uint8
 20  E-Check           7043 non-null   uint8
 21  M-Check           7043 non-null   uint8
dtypes: float64(1), int64(15), uint8(6)
memory usage: 921.8 KB

In [7]:
Telco["Male"] = Telco["Male"].astype(int)
Telco["OY"] = Telco["OY"].astype(int)
Telco["TY"] = Telco["TY"].astype(int)
Telco["Card"] = Telco["Card"].astype(int)
Telco["E-Check"] = Telco["E-Check"].astype(int)
Telco["M-Check"] = Telco["M-Check"].astype(int)

In [8]:
Telco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SeniorCitizen     7043 non-null   int64
 1   Partner           7043 non-null   int64
 2   Dependents        7043 non-null   int64
 3   tenure            7043 non-null   int64
 4   PhoneService      7043 non-null   int64
 5   MultipleLines     7043 non-null   int64
 6   InternetService   7043 non-null   int64
 7   OnlineSecurity    7043 non-null   int64
 8   OnlineBackup      7043 non-null   int64
 9   DeviceProtection  7043 non-null   int64
 10  TechSupport       7043 non-null   int64
 11  StreamingTV       7043 non-null   int64
 12  StreamingMovies   7043 non-null   int64
 13  PaperlessBilling  7043 non-null   int64
 14  MonthlyCharges    7043 non-null   float64
 15  Churn             7043 non-null   int64
 16  Male              7043 non-null   int32
 17  OY                7043 non-null   int32
 18  TY                7043 non-null   int32
 19  Card              7043 non-null   int32
 20  E-Check           7043 non-null   int32
 21  M-Check           7043 non-null   int32
dtypes: float64(1), int32(6), int64(15)
memory usage: 1.0 MB

In [9]:
Y.head(15)

0     0
1     0
2     1
3     0
4     1
5     1
6     0
7     0
8     1
9     0
10    0
11    0
12    0
13    1
14    0
Name: Churn, dtype: int64

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [11]:
len(X_train)

5634

In [12]:
len(X_test)

1409

In [13]:
Result = LogisticRegression()
Result.fit(X_train, Y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [14]:
Result.score(X_train, Y_train)

0.8045793397231097

In [16]:
print("Employee One Result",Result.predict([[0, 1, 1, 13, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 49.95, 1, 0, 0, 0, 0, 1]]))
print("Employee Two Result",Result.predict([[0, 0, 0, 66, 1, 0, 2, 1, 0, 1, 0, 1, 1, 1, 105.65, 1, 0, 1, 0, 0, 0]]))
print("Employee Three Result",Result.predict([[1, 1, 0, 4, 1, 1, 2, 0, 0, 0, 0, 0, 0, 1, 74.40, 1, 0, 0, 0, 0, 1]]))
print("Employee Four Result",Result.predict([[1, 0, 1, 20, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 95.60, 0, 1, 1, 1,0, 0]]))

Employee One Result [0]
Employee Two Result [0]
Employee Three Result [1]
Employee Four Result [0]